# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jayanth Visweswaran
email: jayanth@email.com
description: > # this means to ignore newlines until "baseurl:"
  I think I'm going to write stuff here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: goose_42
github_username:  goose42
linkedin_username: jayanth-visweswaran-6b931464

# Build settings
markdown: kramdown

# Gems
gems:
  - jemoji
